name: unit_test_example
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  test: ^1.17.11

dev_dependencies:
  pedantic: ^1.10.0
  mocktail: ^0.1.4